### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by ck2194** [Trovemaster/exocross#11]
Hi,

I run xcross via a windows subsystem for linux-Ubuntu (WSL). When I perform a simple "./xcross.exe <inputfile> outputfile" command, I get the following error:

me@DESKTOP:/mnt/c/Users/me/desktop/exocross$ make
gfortran -c accuracy.f90 -O3 -fopenmp -std=f2008 -ffree-line-length-512
gfortran -c timer.f90 -O3 -fopenmp -std=f2008 -ffree-line-length-512
gfortran -c input.f90 -O3 -fopenmp -std=f2008 -ffree-line-length-512
gfortran -c VoigtKampff.f90 -O3 -fopenmp -std=f2008 -ffree-line-length-512
gfortran -c phoenix.f90 -O3 -fopenmp -std=f2008 -ffree-line-length-512
gfortran -c spectrum.f90 -O3 -fopenmp -std=f2008 -ffree-line-length-512
gfortran -c crosssections.f90 -O3 -fopenmp -std=f2008 -ffree-line-length-512
gfortran -o xcross.exe accuracy.o  timer.o input.o spectrum.o VoigtKampff.o  phoenix.o -O3 -fopenmp -std=f2008 -ffree-line-length-512 crosssections.o  -static
/usr/lib/gcc/x86_64-linux-gnu/7/libgomp.a(target.o): In function `gomp_target_init':
(.text+0x8b): warning: Using 'dlopen' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking

me@DESKTOP:/mnt/c/Users/me/desktop/exocross$ ./xcross.exe < "input/NaH_gauss_298K_0.5.inp" > "input/output.txt"

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:
#0  0x42da6d in ???
#1  0x42d0e3 in ???
#2  0x4a8b1f in ???
        at /build/glibc-S9d2JN/glibc-2.27/nptl/../sysdeps/unix/sysv/linux/x86_64/sigaction.c:0
#3  0x0 in ???
Segmentation fault (core dumped)

----------------------------------------------------------------------------------------------------------------------------------------------

Any idea what's wrong?

Thanks!

**Comment by ck2194** [comment]
-

**Comment by ck2194** [comment]
I removed the "-static" option and it runs.
